"""Init

Revision ID: 3c49067ec75f
Revises: 85eed6d76fe0
Create Date: 2023-04-02 10:30:42.358051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c49067ec75f'
down_revision = '85eed6d76fe0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
