"""Init

Revision ID: 8c1ccbd5f581
Revises: bf494c5e95d3
Create Date: 2023-05-05 21:13:41.984928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1ccbd5f581'
down_revision = 'bf494c5e95d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('contacts', 'surname',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contacts', 'surname',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
