"""Init

Revision ID: bf494c5e95d3
Revises: 3be3ef0a13fe
Create Date: 2023-05-05 15:01:43.157707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf494c5e95d3'
down_revision = '3be3ef0a13fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
